### ISSUE TITLE
[QA] 기능 점검

### ISSUE THREAD

**Issue by ParkSohyunee** [codeit-team-project/taskify#117]
## 💫 About

최신 develop 기능을 점검

## 🔥 To Do
- landingpage , 모바일 화면 점검 
- 계정관리 수정할때 새로고침해야만 변경이 됨 
- 대시보드 생성 모달에서, 모달이 close되지 않음

**Comment by hongjw030** [comment]
제 컴퓨터에선 계정관리 수정에서 새로고침 안해도 변경이 바로 되더라구요...! (한 1초 정도 딜레이로 이전 사진을 보여주긴하지만 일단 자동 변경 반영은 됩니다!!) 
제 컴으로 시연할테니 이 부분은 일단 수정하지 않겠습니다, 감사합니다!!!
