### ISSUE TITLE
[Design] 공통 레이아웃 개선

### ISSUE THREAD

**Issue by HaydenDevK** [codeit-team-project/taskify#98]
## 💫 About
- nav bar, side bar 영역과 겹치지 않도록 처리하는 과정에서 불필요한 스크롤이 생긴 이슈 해결
- 특정 페이지에만 필요한 padding이 공통적으로 적용된 이슈 해결
## 🔥 To Do
- [x] margin 대신 padding으로 변경하기
- [x] padding 필요한 페이지 컴포넌트로 옮기기

**Comment by ParkSohyunee** [comment]
@HaydenDevK @Hongjw030 선혜님 우선 해당 이슈 확인하였습니다. 아래 의견 드립니다. 

1. 위의 To Do 는 진행해 주셔도 무방합니다.
2. 다만 padding이 공통으로 적용이 필요한 부분은 마이대시보드페이지 / 대시보드 수정페이지 / 마이페이지 입니다.
  ㄴ 즉, 지금 상황에서 특정페이지는 반대로 선혜님께서 작업하시고 있는 대시보드 상세페이지 입니다.
  ㄴ 패딩 2rem은 제가 마이대시보드 페이지, 대시보드 수정페이지 작업하면서 대시보드 상세페이지, 마이페이지도 해당 패딩이 적용되는 상황을 발견하여 공통 레이아웃 초기에 적용했습니다. 
  ㄴ 작업 컬럼이 없다보니 각 컬럼 안 패딩이 넓이 전체인거 까지는 파악을 못한상태였습니다.
3. 물론 4개 페이지 모든 부분도 공통레이아웃에 패딩없애고, 각 페이지마다 패딩을 줘서 변경해도 됩니다.(지금 2rem만 공통이고, 각각 패딩이 다른 부분은 각 페이지에 적용시킨 상태, 반응형도 동일)
4. 제 의견을 종합하자면 지금 상황에서 대시보드 수정페이지만 패딩이 2rem 더 적용된 상태로 판단되며, 프로젝트 발표전까지 모든 페이지 수정이 어렵다면 대시보드 상세페이지만 조정하거나 다음 task(발표 후)로 진행하는 것도 괜찮을 듯 싶습니다. 이 부분 의견 부탁드립니다.

**Comment by HaydenDevK** [comment]
넵~!
"모든" 페이지에 적용되는 레이아웃 컴포넌트 특성 상, "모든" 페이지에 해당하는 부분만 적용하는 게 맞다고 생각합니다. (어느 페이지가 다수이고 소수인지가 아니라요.)
이 정도는 필연적으로 발생할 수 있는 수정사항이라고 생각하고 제가 발견했기 때문에 일괄 처리하였습니다!
후순위로 두기에는 불필요한 스크롤을 빨리 없애는 게 좋을 것 같아 바로 작업했습니다!
그래도 혹 각 페이지에 이상이 없는지 한번 씩 확인해주시면 감사드리겠습니다~!🙏🙇🏻‍♀️
